{% set name = "loop" %}
{% set version = "0.17.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/adrianliechti/loop/archive/v{{ version }}.tar.gz
  sha256: 1815f36f722f056b273efc85e3faa54d077d0310d72aa8e466d992fccaabab98

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - loop --help

about:
  home: https://github.com/adrianliechti/loop
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Seamless Development on Kubernetes
  dev_url: https://github.com/adrianliechti/loop

extra:
  recipe-maintainers:
    - danielnachun
