schema_version: 1

context:
  version: "0.20.4"

package:
  name: loop
  version: ${{ version }}

source:
  url: https://github.com/adrianliechti/loop/archive/v${{ version }}.tar.gz
  sha256: 6c6d6f231d577d6f4090a74359159e281f97a9a6e565e87fb1f8ebd1755f832f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - loop --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Seamless Development on Kubernetes
  homepage: https://github.com/adrianliechti/loop
  repository: https://github.com/adrianliechti/loop

extra:
  recipe-maintainers:
    - danielnachun
