schema_version: 1

context:
  version: "0.30.3"

package:
  name: loop
  version: ${{ version }}

source:
  url: https://github.com/adrianliechti/loop/archive/v${{ version }}.tar.gz
  sha256: f481f411b4759e09450302517d9e4a18b0d8ec2374e2d00c0612ed528e8e26c7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - loop --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Seamless Development on Kubernetes
  homepage: https://github.com/adrianliechti/loop
  repository: https://github.com/adrianliechti/loop

extra:
  recipe-maintainers:
    - danielnachun
