schema_version: 1

context:
  version: "0.30.1"

package:
  name: loop
  version: ${{ version }}

source:
  url: https://github.com/adrianliechti/loop/archive/v${{ version }}.tar.gz
  sha256: 152d1456e3d33c5f3040df9d6b294fd298a5afdf1460c89568c2035b2d72926f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - loop --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Seamless Development on Kubernetes
  homepage: https://github.com/adrianliechti/loop
  repository: https://github.com/adrianliechti/loop

extra:
  recipe-maintainers:
    - danielnachun
