schema_version: 1

context:
  version: "0.30.0"

package:
  name: loop
  version: ${{ version }}

source:
  url: https://github.com/adrianliechti/loop/archive/v${{ version }}.tar.gz
  sha256: b0a3ba5d4fbf33686106043f1c4917beb1610826ad1bf0e7b7e3bd5629cd0204

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - loop --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Seamless Development on Kubernetes
  homepage: https://github.com/adrianliechti/loop
  repository: https://github.com/adrianliechti/loop

extra:
  recipe-maintainers:
    - danielnachun
